
03-02-2018 22:41:31:210 - I: 	Bot is sending to many do nothing commands, if this continues it the bot will be killed off
03-02-2018 22:41:31:210 - I: 	Bot sent to many do nothing commands, something is most likely going wrong, please fix your bot. The player's ships will all be marked as destroyed and killed off.
03-02-2018 22:41:31:211 - D: 	Executing bot with following commands python.exe "bot.py" A "C:\Users\user\Desktop\Strategi Algoritma\tubes1stima\Game Engine -  Version 1.2.2\Game Engine\Replays\2018-02-03 22-39-57-489\Phase 2 - Round 94\A"
03-02-2018 22:41:31:211 - I: 	Executing process python.exe "bot.py" A "C:\Users\user\Desktop\Strategi Algoritma\tubes1stima\Game Engine -  Version 1.2.2\Game Engine\Replays\2018-02-03 22-39-57-489\Phase 2 - Round 94\A"
03-02-2018 22:41:31:274 - I: 	Bot has 4000ms to run before it will be forcefully killed
03-02-2018 22:41:31:404 - E: 	Output from bot: Traceback (most recent call last):
03-02-2018 22:41:31:404 - E: 	Output from bot:   File "bot.py", line 144, in <module>
03-02-2018 22:41:31:404 - E: 	Output from bot:     main(args.PlayerKey)
03-02-2018 22:41:31:404 - E: 	Output from bot:   File "bot.py", line 21, in main
03-02-2018 22:41:31:404 - E: 	Output from bot:     greedy(state['OpponentMap']['Cells'], state['PlayerMap']['Owner']['Energy'])
03-02-2018 22:41:31:404 - E: 	Output from bot:   File "bot.py", line 82, in greedy
03-02-2018 22:41:31:404 - E: 	Output from bot:     output_shot(*valid_cell)
03-02-2018 22:41:31:404 - E: 	Output from bot: UnboundLocalError: local variable 'valid_cell' referenced before assignment
03-02-2018 22:41:31:412 - E: 	Output from bot: 
03-02-2018 22:41:31:412 - I: 	Output from bot: 
03-02-2018 22:41:31:414 - I: 	Your bots total execution time was 00:00:00.2033445